addSbtPlugin("com.timushev.sbt"          % "sbt-updates"      % "0.5.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"     % "0.1.20")
addSbtPlugin("org.scalameta"             % "sbt-native-image" % "0.3.0")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"     % "2.1.3")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"     % "0.9.27")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"     % "2.4.3")
